targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          flutter_integration: true
          fallback_strategy: base_locale
          input_directory: lib/i18n
          input_file_pattern: .i18n.json
          output_directory: lib/i18n
          output_file_name: strings.g.dart
