name: credit_manager
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Pub Packages
  floor: ^1.3.0
  dynamic_color: ^1.5.4
  flutter_colorpicker: ^1.0.3
  flutter_native_splash: ^2.0.4
  get_it: ^7.2.0
  provider: ^6.0.4
  slang: ^3.5.0
  slang_flutter: ^3.5.0
  sqflite: ^2.2.2
  freezed_annotation: ^2.2.0
  decimal: ^2.3.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Development dependencies
  flutter_lints: ^2.0.0
  floor_generator: ^1.3.0
  build_runner: ^2.3.2
  slang_build_runner: ^3.5.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4

flutter:
  generate: true
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
